//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriendZoneAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Comment = new HashSet<Comment>();
            this.Post = new HashSet<Post>();
            this.User1 = new HashSet<User>();
        }
    
        public string Email { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public System.DateTime Birthday { get; set; }
        public string Phone { get; set; }
        public string Streetname { get; set; }
        public string Postalcode { get; set; }
        public string ProfilePicture { get; set; }
        public string Partner { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual ICollection<Post> Post { get; set; }
        public virtual ICollection<User> User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
