//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriendZoneWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Couples
    {
        public int ID { get; set; }
        public string HerMail { get; set; }
        public string HisMail { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
