//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriendZoneWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Couples = new HashSet<Couples>();
            this.Couples1 = new HashSet<Couples>();
        }
    
        public string Email { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Phone { get; set; }
        public System.DateTime Birthday { get; set; }
        public string ProfilePicture { get; set; }
        public string Address { get; set; }
    
        public virtual ICollection<Couples> Couples { get; set; }
        public virtual ICollection<Couples> Couples1 { get; set; }
    }
}
